baseURL = 'https://blog.rm-rf.link/'
languageCode = 'en-us'
publishDir = '_site'
theme = "hugo-theme-monochrome"
title = 'Stacheldraht Blog'

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
author = "Oliver Salzburg"
enable_collapsible_toc = true
enable_open_graph = true
enable_site_search = true
enable_zooming_js = true

[taxonomies]
category = 'categories'
tag = 'tags'

[markup.goldmark.renderer]
unsafe = true
